DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS artifacts;
DROP TABLE IF EXISTS metrics;
DROP TABLE IF EXISTS hyperparameters;
DROP TABLE IF EXISTS transformations;
DROP TABLE IF EXISTS pipeline_steps;

ALTER TABLE runs DROP COLUMN IF EXISTS finished_at;
ALTER TABLE runs DROP COLUMN IF EXISTS started_at;
ALTER TABLE runs DROP COLUMN IF EXISTS created_at;
ALTER TABLE runs DROP COLUMN IF EXISTS status;
ALTER TABLE runs DROP COLUMN IF EXISTS git_sha;
ALTER TABLE runs DROP COLUMN IF EXISTS config_hash;
ALTER TABLE runs DROP COLUMN IF EXISTS job_type;

ALTER TABLE datasets DROP COLUMN IF EXISTS original_filename;
ALTER TABLE datasets DROP COLUMN IF EXISTS size_bytes;
ALTER TABLE datasets DROP COLUMN IF EXISTS storage_uri;